# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['alist_drive.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['watchdog.observers.polling', 'watchdog.events', 'cryptography.hazmat.primitives.asymmetric.rsa', 'cryptography.hazmat.primitives.asymmetric.padding', 'cryptography.hazmat.primitives.hashes', 'cryptography.hazmat.primitives.serialization'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'unittest', 'xmlrpc', 'pydoc', 'doctest',
        'distutils', 'lib2to3', 'setuptools', 'pip', 'pkg_resources',
        'email', 'html', 'gzip', 'bz2', 'lzma', 'zipfile',
        'multiprocessing', 'concurrent', 'asyncio',
        'xml.dom', 'xml.sax', 'xml.etree',
        'sqlite3', 'dbm',
        'curses', 'tty', 'pty',
        'venv', 'ensurepip', 'zoneinfo',
        'test', 'tests', 'idlelib', 'pydoc_data',
        'IPython', 'jupyter', 'notebook',
        'numpy', 'pandas', 'matplotlib', 'scipy',
        'PIL', 'cv2', 'requests_oauthlib',
        'sphinx', 'docutils', 'pygments',
        'win32com', 'pythoncom', 'pywintypes',
        'tornado', 'gevent', 'zmq',],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MorongDisk',
    icon='morong.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_client.txt',
    manifest='MorongDisk.manifest',
)
